// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6-aOfSXGnZ4UV4UnfEr57bXdMRKuRic',
    appId: '1:296115737176:web:e2e40bdeb4201a6ecf302d',
    messagingSenderId: '296115737176',
    projectId: 'todo-app-53b6a',
    authDomain: 'todo-app-53b6a.firebaseapp.com',
    storageBucket: 'todo-app-53b6a.firebasestorage.app',
    measurementId: 'G-3VWNYJ28QH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg75KtCdAsMIliLTTpvuSUABYUqDn-mkk',
    appId: '1:296115737176:android:6a33d8de46a5df4dcf302d',
    messagingSenderId: '296115737176',
    projectId: 'todo-app-53b6a',
    storageBucket: 'todo-app-53b6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdz2BSStOeDqBgV_L5Lm7NA9o5ZbyIjao',
    appId: '1:296115737176:ios:79d24631db59b781cf302d',
    messagingSenderId: '296115737176',
    projectId: 'todo-app-53b6a',
    storageBucket: 'todo-app-53b6a.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
